name: chip_pos
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0-334.2.beta

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.0
  path: ^1.9.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  connectivity_plus: ^6.0.5
  fl_chart: ^0.69.0
  curved_navigation_bar: ^1.0.6
  intl: ^0.19.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.3
  firebase_auth: ^5.3.1
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Coffee
      fonts:
        - asset: assets/fonts/Coffee Soda.ttf
