// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiy8l4sTX46dim8mGXuVOcPUYJSlWxRO0',
    appId: '1:716926455817:web:99b82da418e185adcb68d8',
    messagingSenderId: '716926455817',
    projectId: 'burgergembong',
    authDomain: 'burgergembong.firebaseapp.com',
    storageBucket: 'burgergembong.appspot.com',
    measurementId: 'G-V5YY6320GB',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNcwZdm9d5hK1g-jIsqhmo8vDFOwJYP8Y',
    appId: '1:716926455817:ios:716f7ef940575355cb68d8',
    messagingSenderId: '716926455817',
    projectId: 'burgergembong',
    storageBucket: 'burgergembong.appspot.com',
    iosBundleId: 'com.example.chipPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNcwZdm9d5hK1g-jIsqhmo8vDFOwJYP8Y',
    appId: '1:716926455817:ios:716f7ef940575355cb68d8',
    messagingSenderId: '716926455817',
    projectId: 'burgergembong',
    storageBucket: 'burgergembong.appspot.com',
    iosBundleId: 'com.example.chipPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiy8l4sTX46dim8mGXuVOcPUYJSlWxRO0',
    appId: '1:716926455817:web:a63ebdf74c1c89c1cb68d8',
    messagingSenderId: '716926455817',
    projectId: 'burgergembong',
    authDomain: 'burgergembong.firebaseapp.com',
    storageBucket: 'burgergembong.appspot.com',
    measurementId: 'G-M0KZS5DS1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIUxP46mjEQrhLQY4QZzjnU4X-ypAZOaE',
    appId: '1:716926455817:android:d2764d6242999a7bcb68d8',
    messagingSenderId: '716926455817',
    projectId: 'burgergembong',
    storageBucket: 'burgergembong.appspot.com',
  );

}